### ISSUE TITLE
[upgrade]  from 2.8~ynh1 to 2.8~ynh2  is KO

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/pytition_ynh#28]
### Describe the bug
simple upgrade is failing

`# yunohost app upgrade pytition`

### Context

- Hardware: *VPS*
- YunoHost version: 
```
root@krashboyz:~# yunohost --version
yunohost: 
  repo: stable
  version: 11.2.10.1
yunohost-admin: 
  repo: stable
  version: 11.2.4.1
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2
```
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: `2.8~ynh2`
- If upgrading, current package version: *2.8~ynh1*

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
`# yunohost app upgrade pytition`

### Logs

https://paste.yunohost.org/raw/acimetoguh

thx for your help :)

isAAAc
